### ISSUE TITLE
indexing issue in README examples?

### ISSUE THREAD

**Issue by DylanMG** [SOLV-Code/MetricsCOSEWIC#61]
When I run multiFit in both of the examples I get 
``Error in out.mat["Jags_Med", "probdecl"] <- round(est.jags$probdecl, 5) : 
  number of items to replace is not a multiple of replacement length``
and the function breaks. 

Might have to do with indexing? I restarted R to double check and the issue persisted.

**Comment by SOLV-Code** [comment]
Welcome to the package! 
I think what you are running into is that we made some recent tweaks to the core package functions (with [this merge](https://github.com/SOLV-Code/MetricsCOSEWIC/commit/1b6ade7a7a0223db32fe89f1792aaf3e73d2dc91)) to accommodate requested features for the shiny app , and did not get around yet to update the wrapper functions like *multiFit()*.

Specifically, the fn (calcPercChangeMCMC)[https://github.com/SOLV-Code/MetricsCOSEWIC/blob/main/R/Module_calcPercChangeMCMC.R] now takes multiple BM values (-30,-50,-70) for the ProbDecl calculation, when it previously only took 1 value. The corresponding output object changed from a value to data frame, which breaks the summary as you found above.

Things are really hectic right now, so I wasn't planning to work on this package until early April. Are you using this actively right now, or just exploring the package?

**Comment by carrieholt** [comment]
Yes, later this year, we will be developing a STAN version of this code with more flexibility and exploration of the priors. Please get in touch by email if interested, and/or stay tuned for updates here. Also, thanks for catching this bug, which has cropped up from the revisions to the code for the Shiny App which takes multiple BM values (as mentioned above). 
Gottfried, thanks for agreeing to look at this in April.
And thanks for your interest!

**Comment by DylanMG** [comment]
Thanks for the replies. I'm exploring the package. Looking forward to the updates. I'll keep watching and be in touch.

**Comment by SOLV-Code** [comment]
This is the same issue as #62, so closing this one
