### ISSUE TITLE
Fixing NA handling in calcPerChangeSimple()

### ISSUE THREAD

**Issue by carrieholt** [SOLV-Code/MetricsCOSEWIC#66]
Instead of requiring  pchange = NA if there are any NAs in the input time-series, we can revise the code so the x-axis (yrs) is the index of years instead of 0:(n-1). This way we can estimate MLEs of percent change with NAs in the log(Abundance) time-series.

To do this, I suggest replacing this line:
https://github.com/SOLV-Code/MetricsCOSEWIC/blob/94d05ffe62475b0a77a61a2eb8e1b360e1d88c48/R/Module_calcPercChangeSimple.R#L20

with this code:
missing <- as.numeric(!is.na(vec.in)) # vector indicating which input values are missing

ny <- 1 
yrs <- NA # index of years to use in the regression, built in the loop below
for (i in 1:length(vec.in)) {
  if (missing[i]) {
    yrs[ny] = i
    ny = ny + 1
  }
}
yrs <- yrs -1 # to make years start at 0, as before

And then removing this line:
https://github.com/SOLV-Code/MetricsCOSEWIC/blob/94d05ffe62475b0a77a61a2eb8e1b360e1d88c48/R/Module_calcPercChangeSimple.R#L30

**Comment by SOLV-Code** [comment]
I do remember that in earlier discussions there were concerns raised re: the following:
- number of NA you can have and still do a Perc change calc (no more than 2 of 15?, 4 of 15?, 7 of 15?)
-  places in the time series where the NA values are (if 3 values are missing at various spots in a 12 year series, it may be fine, but if 3 values from the last 4-year generation are missing, maybe that should result in an NA value for the perc change)
- handling on NA values with the generational smoothing step (if 1 year is missing, should that trigger 3 NA values in the running average for a 4-yr generation?)

Based on all of these, we decided at the time to enforce a "no missing values rule", and punt the decision to end users to infill the time series *before* feeding it into the function, if that makes sense for their specific case.

**Comment by carrieholt** [comment]
Let's keep with the rule that there needs to be at least 50% data (<50% NAs in the time -series). In the future, we could add another rule that there needs to be at least one data point in the last generation. However, so far, we haven't required generation time as an input, which would need to be added in that case.  In the "calcPercChangeSimple()" function (the function that is called in the current version of comparePercChange(), there is no generational smoothing, so NA handling there is not an issue; same for Bayes implementations. For COSEWIC applications, smoothing should be done a priori when/if required. It will not be required for many/most taxonomic groups.

**Comment by SOLV-Code** [comment]
Makes sense.
