### ISSUE TITLE
Minor typo in testing script

### ISSUE THREAD

**Issue by carrieholt** [SOLV-Code/MetricsCOSEWIC#67]
The du.df input for this function is a two column dataframe, not three column dataframe (which test.data currently is)
https://github.com/SOLV-Code/MetricsCOSEWIC/blob/94d05ffe62475b0a77a61a2eb8e1b360e1d88c48/TestingScripts/DEV_BugReport_Num61%2662.R#L54-L61

I suggest revising line 55 to:
du.df = test.data %>% select(Year, Abd),

Note, we do need the 3 column test.data for a function further down in the code; this simple fix here for this function should work.

**Comment by SOLV-Code** [comment]
thank you, please implement as you work through

**Comment by carrieholt** [comment]
Merged.
